
- name: AdaBoostClassifier
  module:
    imports:
      - sklearn.ensemble
    method: AdaBoostClassifier 
  parameters: 
      random_state : 44
      max_depth: 200


- name: BaggingClassifier
  module:
    imports:
      - sklearn.ensemble 
    method: BaggingClassifier
  parameters: 
      random_state : 44
      max_depth: 200



- name: RandomForestClassifier
  module:
    imports:
      - sklearn.ensemble
    method: RandomForestClassifier
  parameters: 
      random_state : 44









