basePath: /
host: localhost:8080
info:
  contact:
    email: contact@pureml.com
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: PureML API Documentation
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
